// jsbuild 将 JavaScript 文件打包成独立的可执行程序。
//
// 原理: 把入口 JS 及其相对 import 的模块嵌入一个生成的 Go 工程,
// 然后调用 `go build` 编译成单个 .exe。生成的程序自带 Gox,
// 运行时会话临时目录中解压脚本, 再通过现有的 vm.EvalFile 执行,
// 因此 import/export 模块也能正常工作。完全复用现有代码, 不改动任何
// Gox 的源文件。
//
// 用法:
//
//	jsbuild <input.js> [-o output.exe] [--name 应用名] [--windowed] [--verbose]
package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
)

// importRe 匹配 import/export ... from "./xxx" 的相对路径模块。
// 只收集以 . 开头的相对路径, 忽略内置/绝对路径。
var importRe = regexp.MustCompile(`(?m)^\s*(?:import|export)\b[^;]*?\bfrom\s+["'](\.[^"']+)["']`)

// appMainGo 是生成的应用入口模板。
// 运行: 解压嵌入的 JS → vm.EvalFile 执行 → 打印顶层结果 → 跑定时器事件循环。
// __APPNAME__ 占位符会被替换为应用名。
const appMainGo = `// Code generated by jsbuild. DO NOT EDIT.
package main

import (
	"embed"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/14752222/Gox/compiler"
	"github.com/14752222/Gox/lexer"
	"github.com/14752222/Gox/object"
	"github.com/14752222/Gox/parser"
	"github.com/14752222/Gox/stdlib"
	"github.com/14752222/Gox/vm"
)

//go:embed all:app
var appFS embed.FS

func main() {
	// 将嵌入的脚本解压到临时目录, 使相对 import 可解析
	tmp, err := os.MkdirTemp("", "jsapp-*")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: cannot create temp dir: %v\n", err)
		os.Exit(1)
	}
	defer os.RemoveAll(tmp)

	if err := extractFS(appFS, "app", tmp); err != nil {
		fmt.Fprintf(os.Stderr, "error: cannot extract scripts: %v\n", err)
		os.Exit(1)
	}

	entry := filepath.Join(tmp, "main.js")
	source, err := os.ReadFile(entry)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: cannot read entry script: %v\n", err)
		os.Exit(1)
	}

	l := lexer.New(string(source))
	p := parser.New(l)
	program := p.ParseProgram()
	if p.Errors().HasErrors() {
		fmt.Fprintf(os.Stderr, "parser errors:\n%s\n", p.Errors().String())
		os.Exit(1)
	}

	c := compiler.New()
	if err := c.Compile(program); err != nil {
		fmt.Fprintf(os.Stderr, "compiler error: %v\n", err)
		os.Exit(1)
	}

	runtimeVM := vm.NewWithGlobals(c.Bytes(), c.Constants(), c.NumLocals(), stdlib.SetupGlobals())
	runtimeVM.SetModuleBase(filepath.Dir(entry))
	if err := runtimeVM.RunCompiled(c); err != nil {
		fmt.Fprintf(os.Stderr, "runtime error: %v\n", err)
		os.Exit(1)
	}

	// 打印顶层表达式结果 (非 undefined)
	if result := runtimeVM.LastPopped(); result != nil {
		if _, isUndef := result.(*object.Undefined); !isUndef {
			fmt.Println(result.Inspect())
		}
	}

	// 运行定时器事件循环, 让 setTimeout/setInterval 及严格定时器回调执行完毕
	if err := runtimeVM.RunTimers(); err != nil {
		fmt.Fprintf(os.Stderr, "timer error: %v\n", err)
		os.Exit(1)
	}
}

// extractFS 将 embed.FS 中 prefix 下的所有文件复制到 dest 目录。
func extractFS(fsys fs.FS, prefix, dest string) error {
	return fs.WalkDir(fsys, prefix, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(prefix, path)
		if err != nil {
			return err
		}
		data, err := fs.ReadFile(fsys, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dest, rel)
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		return os.WriteFile(target, data, 0o644)
	})
}
`

// appMainGoGUI 是 GUI 应用的入口模板 (P3)。
// 与 CLI 模板的差异: LockOSThread + 窗口消息泵事件循环 (gfx.Pump);
// 脚本未创建窗口时回落到普通定时器循环。
const appMainGoGUI = `// Code generated by jsbuild (GUI mode). DO NOT EDIT.
package main

import (
	"embed"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"

	"github.com/14752222/Gox/compiler"
	"github.com/14752222/Gox/gfx"
	_ "github.com/14752222/Gox/gfx/backend" // 按目标平台注册窗口后端
	"github.com/14752222/Gox/lexer"
	"github.com/14752222/Gox/object"
	"github.com/14752222/Gox/parser"
	"github.com/14752222/Gox/stdlib"
	"github.com/14752222/Gox/vm"
)

//go:embed all:app
var appFS embed.FS

func main() {
	// GUI 模式: 窗口消息投递到创建线程, 主 goroutine 必须锁定 OS 线程
	runtime.LockOSThread()

	tmp, err := os.MkdirTemp("", "jsapp-*")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: cannot create temp dir: %v\n", err)
		os.Exit(1)
	}
	defer os.RemoveAll(tmp)

	if err := extractFS(appFS, "app", tmp); err != nil {
		fmt.Fprintf(os.Stderr, "error: cannot extract scripts: %v\n", err)
		os.Exit(1)
	}

	entry := filepath.Join(tmp, "main.js")
	source, err := os.ReadFile(entry)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: cannot read entry script: %v\n", err)
		os.Exit(1)
	}

	l := lexer.New(string(source))
	p := parser.New(l)
	program := p.ParseProgram()
	if p.Errors().HasErrors() {
		fmt.Fprintf(os.Stderr, "parser errors:\n%s\n", p.Errors().String())
		os.Exit(1)
	}

	c := compiler.New()
	if err := c.Compile(program); err != nil {
		fmt.Fprintf(os.Stderr, "compiler error: %v\n", err)
		os.Exit(1)
	}

	runtimeVM := vm.NewWithGlobals(c.Bytes(), c.Constants(), c.NumLocals(), stdlib.SetupGlobals())
	runtimeVM.SetModuleBase(filepath.Dir(entry))
	if err := runtimeVM.RunCompiled(c); err != nil {
		fmt.Fprintf(os.Stderr, "runtime error: %v\n", err)
		os.Exit(1)
	}

	// GUI 模式下不打印 (P3-6): render() 返回窗口句柄对象, 打印出来纯属噪音。
	// 判据与 main.go 一致 —— 看"有没有挂载窗口", 而不是值的类型。
	if result := runtimeVM.LastPopped(); result != nil && !gfx.Active() {
		if _, isUndef := result.(*object.Undefined); !isUndef {
			fmt.Println(result.Inspect())
		}
	}

	// 事件循环: 脚本创建了窗口 (gfx.Active) 用消息泵驱动, 否则跑定时器
	var loopErr error
	if gfx.Active() {
		loopErr = runtimeVM.RunTimersWithPump(gfx.Pump)
	} else {
		loopErr = runtimeVM.RunTimers()
	}
	if loopErr != nil {
		fmt.Fprintf(os.Stderr, "timer error: %v\n", loopErr)
		os.Exit(1)
	}
}

// extractFS 将 embed.FS 中 prefix 下的所有文件复制到 dest 目录。
func extractFS(fsys fs.FS, prefix, dest string) error {
	return fs.WalkDir(fsys, prefix, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(prefix, path)
		if err != nil {
			return err
		}
		data, err := fs.ReadFile(fsys, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dest, rel)
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		return os.WriteFile(target, data, 0o644)
	})
}
`

const goModTemplate = `module jsapp

go 1.26.2

require github.com/14752222/Gox v0.0.0

replace github.com/14752222/Gox => %s
`

func main() {
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: jsbuild <input.js> [options]\n\n")
		fmt.Fprintf(os.Stderr, "把 JavaScript 文件打包成独立的桌面可执行程序 (.exe)。\n")
		fmt.Fprintf(os.Stderr, "自动收集并嵌入相对 import 的模块文件, 不改动 Gox 源码。\n\n")
		fmt.Fprintf(os.Stderr, "Options:\n")
		fmt.Fprintf(os.Stderr, "  -o, --out <path>     输出文件路径 (默认: <输入文件名>.exe)\n")
		fmt.Fprintf(os.Stderr, "      --name <name>    应用名 (用于错误信息显示, 默认取输入文件名)\n")
		fmt.Fprintf(os.Stderr, "      --windowed       窗口模式: 不显示控制台窗口 (仅 Windows)\n")
		fmt.Fprintf(os.Stderr, "      --gui            GUI 应用: 窗口消息泵事件循环 (配合 gx/gfx render)\n")
		fmt.Fprintf(os.Stderr, "      --target <os>/<arch>  交叉编译目标 (windows|linux|darwin / amd64|arm64|386),\n")
		fmt.Fprintf(os.Stderr, "                          如 linux/amd64; 非 Windows 目标默认输出不带 .exe\n")
		fmt.Fprintf(os.Stderr, "  -v, --verbose        显示构建过程输出\n")
		fmt.Fprintf(os.Stderr, "  -h, --help           显示帮助\n")
	}

	// 手动解析参数: 支持 flag 出现在位置参数之前或之后
	var (
		out        string
		name       string
		windowed   bool
		gui        bool
		verbose    bool
		targetOS   string
		targetArch string
		positional []string
	)
	args := os.Args[1:]
	for i := 0; i < len(args); i++ {
		a := args[i]
		switch {
		case a == "-h" || a == "--help":
			flag.Usage()
			os.Exit(0)
		case a == "-o" || a == "--out":
			if i+1 >= len(args) {
				fatal("flag %s requires a value", a)
			}
			i++
			out = args[i]
		case a == "--name":
			if i+1 >= len(args) {
				fatal("flag %s requires a value", a)
			}
			i++
			name = args[i]
		case a == "--windowed":
			windowed = true
		case a == "--gui":
			gui = true
		case a == "--target":
			if i+1 >= len(args) {
				fatal("flag %s requires a value", a)
			}
			i++
			spec := args[i]
			osPart, archPart, ok := strings.Cut(spec, "/")
			if !ok {
				osPart, archPart = spec, ""
			}
			targetOS = strings.ToLower(osPart)
			targetArch = strings.ToLower(archPart)
			switch targetOS {
			case "windows", "linux", "darwin":
			default:
				fatal("--target: unsupported os %q (windows|linux|darwin)", targetOS)
			}
			if targetArch != "" {
				switch targetArch {
				case "amd64", "arm64", "386":
				default:
					fatal("--target: unsupported arch %q (amd64|arm64|386)", targetArch)
				}
			}
		case a == "--verbose" || a == "-v":
			verbose = true
		case strings.HasPrefix(a, "-"):
			fatal("unknown flag: %s", a)
		default:
			positional = append(positional, a)
		}
	}

	if len(positional) < 1 {
		flag.Usage()
		os.Exit(2)
	}
	input := positional[0]

	absInput, err := filepath.Abs(input)
	if err != nil {
		fatal("cannot resolve input path: %v", err)
	}
	source, err := os.ReadFile(absInput)
	if err != nil {
		fatal("cannot read %s: %v", input, err)
	}

	// 收集入口及其相对 import 的所有模块文件
	files := map[string][]byte{}
	files[absInput] = source
	if err := collectModules(absInput, source, files, verbose); err != nil {
		fatal("%v", err)
	}

	// 定位 Gox 项目根目录 (本打包器所在目录的上级)
	_, thisFile, _, _ := runtime.Caller(0)
	projectRoot := filepath.Dir(filepath.Dir(thisFile))
	if _, err := os.Stat(filepath.Join(projectRoot, "go.mod")); err != nil {
		fatal("cannot locate Gox project root (looking for go.mod in %s)", projectRoot)
	}

	// 创建临时构建目录
	tmp, err := os.MkdirTemp("", "jsbuild-*")
	if err != nil {
		fatal("cannot create temp dir: %v", err)
	}
	defer os.RemoveAll(tmp)

	// 写入 go.mod
	goMod := fmt.Sprintf(goModTemplate, filepath.ToSlash(projectRoot))
	if err := os.WriteFile(filepath.Join(tmp, "go.mod"), []byte(goMod), 0o644); err != nil {
		fatal("cannot write go.mod: %v", err)
	}

	// 写入 main.go (替换应用名占位符; GUI 模式用带消息泵的模板)
	template := appMainGo
	if gui {
		template = appMainGoGUI
	}
	appSrc := strings.ReplaceAll(template, "__APPNAME__", name)
	if err := os.WriteFile(filepath.Join(tmp, "main.go"), []byte(appSrc), 0o644); err != nil {
		fatal("cannot write main.go: %v", err)
	}

	// 写入 app/ 目录下的 JS 文件
	appDir := filepath.Join(tmp, "app")
	if err := os.MkdirAll(appDir, 0o755); err != nil {
		fatal("cannot create app dir: %v", err)
	}
	baseDir := filepath.Dir(absInput)
	for path, data := range files {
		// 入口脚本固定命名为 main.js, 模块按相对入口目录的路径存放
		rel := "main.js"
		if path != absInput {
			var err error
			rel, err = filepath.Rel(baseDir, path)
			if err != nil {
				fatal("cannot compute relative path for %s: %v", path, err)
			}
			rel = filepath.ToSlash(rel)
		}
		dest := filepath.Join(appDir, rel)
		if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
			fatal("cannot create dir for %s: %v", dest, err)
		}
		if err := os.WriteFile(dest, data, 0o644); err != nil {
			fatal("cannot write %s: %v", dest, err)
		}
	}

	// 确定输出路径: 非 Windows 目标默认不带 .exe 后缀
	output := out
	if output == "" {
		output = strings.TrimSuffix(absInput, filepath.Ext(absInput))
		if targetOS == "" || targetOS == "windows" {
			output += ".exe"
		} else if targetArch != "" {
			output += "-" + targetOS + "-" + targetArch
		} else {
			output += "-" + targetOS
		}
	}
	outputAbs, err := filepath.Abs(output)
	if err != nil {
		fatal("cannot resolve output path: %v", err)
	}

	// 交叉编译环境 (GOOS/GOARCH); tidy 与 build 使用同一套环境,
	// 保证依赖解析与构建目标一致
	buildEnv := os.Environ()
	if targetOS != "" {
		buildEnv = append(buildEnv, "GOOS="+targetOS)
	}
	if targetArch != "" {
		buildEnv = append(buildEnv, "GOARCH="+targetArch)
	}

	// 先整理依赖 (GUI 模板经 gfx 引入 x/image 等; 依赖已在本地模块缓存,
	// 通常无需联网), 生成 go.sum 后再构建
	tidy := exec.Command("go", "mod", "tidy")
	tidy.Dir = tmp
	tidy.Env = buildEnv
	if verbose {
		tidy.Stdout = os.Stdout
	}
	tidy.Stderr = os.Stderr
	if err := tidy.Run(); err != nil {
		fatal("go mod tidy failed: %v", err)
	}

	// 调用 go build (-trimpath 去除本机路径; -H windowsgui 仅对 Windows 目标)
	ldflags := "-s -w"
	if windowed && (targetOS == "" || targetOS == "windows") {
		ldflags += " -H windowsgui"
	}
	buildArgs := []string{"build", "-trimpath", "-ldflags", ldflags, "-o", outputAbs, "."}
	if verbose {
		fmt.Printf("go %s\n", strings.Join(buildArgs, " "))
	}
	cmd := exec.Command("go", buildArgs...)
	cmd.Dir = tmp
	cmd.Env = buildEnv
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		fatal("go build failed: %v", err)
	}

	target := ""
	if targetOS != "" {
		target = " [" + targetOS
		if targetArch != "" {
			target += "/" + targetArch
		}
		target += "]"
	}
	fmt.Printf("OK: %s%s (%d JS files embedded)\n", outputAbs, target, len(files))
}

// collectModules 递归收集 source 中相对 import 的模块文件。
func collectModules(entry string, source []byte, files map[string][]byte, verbose bool) error {
	for _, m := range importRe.FindAllSubmatch(source, -1) {
		spec := string(m[1])
		modPath := filepath.Clean(filepath.Join(filepath.Dir(entry), spec))
		if _, ok := files[modPath]; ok {
			continue
		}
		data, err := os.ReadFile(modPath)
		if err != nil {
			return fmt.Errorf("cannot read module '%s' (imported from %s): %v", spec, entry, err)
		}
		if verbose {
			fmt.Printf("  embed module: %s\n", modPath)
		}
		files[modPath] = data
		if err := collectModules(modPath, data, files, verbose); err != nil {
			return err
		}
	}
	return nil
}

func fatal(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "jsbuild: "+format+"\n", args...)
	os.Exit(1)
}
