// Code generated by scripts/gen-props-golden.py. DO NOT EDIT.
//
// 真源是 gfx/*.go 的属性**读取点**（写入点不算），由 tools/propdump
// 用 go/ast + 调用图抽出后按标签归拢；机器可读的同一份数据在
// docs/props.golden.json。改了 gfx 的读取点后跑
// python3 scripts/gen-props-golden.py 重新生成 —— CI 有 diff 闸门。
package gfx

// knownPropsUniversal 是所有标签都读的属性。
//
// 「判不出标签归属就落这里」是刻意的：过宽只是漏报（少警告一次），过窄
// 才是误报（警告一个真在用的属性），而误报会让人直接把 strictAPI 关掉。
var knownPropsUniversal = map[string]struct{}{
	"accept":           {},
	"aria-description": {},
	"aria-hidden":      {},
	"aria-label":       {},
	"autoplay":         {},
	"background":       {},
	"border":           {},
	"borderStyle":      {},
	"borderWidth":      {},
	"buffer":           {},
	"checked":          {},
	"color":            {},
	"colors":           {},
	"columns":          {},
	"controls":         {},
	"current":          {},
	"cursor":           {},
	"delay":            {},
	"description":      {},
	"disabled":         {},
	"ellipsis":         {},
	"escapeClipping":   {},
	"filter":           {},
	"flexGrow":         {},
	"flexShrink":       {},
	"focusable":        {},
	"font":             {},
	"fontFamily":       {},
	"fontStyle":        {},
	"fontWeight":       {},
	"fullscreen":       {},
	"gap":              {},
	"height":           {},
	"hidden":           {},
	"hideFocusRing":    {},
	"itemHeight":       {},
	"key":              {},
	"left":             {},
	"letterSpacing":    {},
	"level":            {},
	"lineHeight":       {},
	"longPressDelay":   {},
	"longPressSlop":    {},
	"loop":             {},
	"margin":           {},
	"max":              {},
	"maxHeight":        {},
	"maxWidth":         {},
	"min":              {},
	"minHeight":        {},
	"minWidth":         {},
	"modal":            {},
	"multiple":         {},
	"muted":            {},
	"name":             {},
	"nodes":            {},
	"opacity":          {},
	"open":             {},
	"options":          {},
	"padding":          {},
	"paddingBottom":    {},
	"paddingLeft":      {},
	"paddingRight":     {},
	"paddingTop":       {},
	"pageSize":         {},
	"placeholder":      {},
	"placement":        {},
	"playing":          {},
	"position":         {},
	"radius":           {},
	"resizable":        {},
	"role":             {},
	"shadow":           {},
	"side":             {},
	"src":              {},
	"step":             {},
	"swipeThreshold":   {},
	"tabIndex":         {},
	"text":             {},
	"theme":            {},
	"title":            {},
	"top":              {},
	"total":            {},
	"transition":       {},
	"value":            {},
	"vlist":            {},
	"volume":           {},
	"width":            {},
	"wrap":             {},
	"x":                {},
	"y":                {},
	"zIndex":           {},
}

// knownPropsByTag 是各标签**额外**认得的属性（不含 universal 那一档）。
var knownPropsByTag = map[string]map[string]struct{}{
	"alert": {
		"closable":  {},
		"closeable": {},
	},
	"avatar": {
		"shape": {},
		"size":  {},
	},
	"badge": {
		"count": {},
		"dot":   {},
	},
	"column": {
		"alignItems":     {},
		"avoidReserved":  {},
		"justifyContent": {},
	},
	"empty": {
		"desc": {},
	},
	"form": {
		"alignItems":     {},
		"avoidReserved":  {},
		"justifyContent": {},
	},
	"grid": {
		"alignItems": {},
	},
	"icon": {
		"size": {},
	},
	"label": {
		"align":    {},
		"required": {},
	},
	"list-item": {
		"alignItems":     {},
		"avoidReserved":  {},
		"divider":        {},
		"justifyContent": {},
		"selected":       {},
	},
	"menu": {
		"label": {},
	},
	"menubar": {
		"label": {},
	},
	"menuitem": {
		"label":    {},
		"shortcut": {},
	},
	"row": {
		"alignItems":     {},
		"avoidReserved":  {},
		"justifyContent": {},
	},
	"scroll": {
		"alignItems":    {},
		"avoidReserved": {},
		"scrollLeft":    {},
		"scrollTop":     {},
	},
	"select-popup": {
		"alignItems":     {},
		"avoidReserved":  {},
		"justifyContent": {},
	},
	"separator": {
		"vertical": {},
	},
	"skeleton": {
		"active":     {},
		"avatar":     {},
		"rows":       {},
		"titleWidth": {},
	},
	"slot": {
		"alignItems":     {},
		"avoidReserved":  {},
		"justifyContent": {},
	},
	"spinner": {
		"size": {},
	},
	"tab": {
		"alignItems":     {},
		"avoidReserved":  {},
		"justifyContent": {},
	},
	"table": {
		"rows": {},
	},
	"table-cell": {
		"borderless": {},
	},
	"table-row": {
		"_zebra":     {},
		"borderless": {},
	},
	"tag": {
		"closable":  {},
		"closeable": {},
	},
	"textarea": {
		"rows": {},
	},
	"toast": {
		"message": {},
	},
	"video": {
		"fit":    {},
		"poster": {},
	},
	"view": {
		"alignItems":     {},
		"avoidReserved":  {},
		"justifyContent": {},
	},
}

// knownEventsUniversal 是所有标签都能收到的事件（内核有派发点）。
var knownEventsUniversal = map[string]struct{}{
	"onBlur":        {},
	"onChange":      {},
	"onClick":       {},
	"onClose":       {},
	"onContextMenu": {},
	"onEnded":       {},
	"onError":       {},
	"onFocus":       {},
	"onInput":       {},
	"onKeyDown":     {},
	"onKeyUp":       {},
	"onLongPress":   {},
	"onMouseMove":   {},
	"onMove":        {},
	"onPause":       {},
	"onPlay":        {},
	"onReady":       {},
	"onResize":      {},
	"onRowClick":    {},
	"onScroll":      {},
	"onSearch":      {},
	"onSelect":      {},
	"onSubmit":      {},
	"onSwipe":       {},
	"onTimeUpdate":  {},
	"onWheel":       {},
}

// knownEventsByTag 是各标签**额外**认得的事件。
var knownEventsByTag = map[string]map[string]struct{}{}

// eventsNotImplemented 是**对外承诺过但内核还没有派发点**的事件。
//
// 这一档必须单独报：把它们混进「未知属性」会让人去查自己脚本的拼写，
// 查一天也查不出来 —— 问题是内核还没写。值是给用户的说明。
var eventsNotImplemented = map[string]string{
	"onMouseLeave": "docs/gui-patterns.md:309 把 <button onMouseLeave={…}> 当示例写，平台层有 EventMouseLeave，但 gfx 没有派发点（没有 callHandler）—— 回调永远不会被调用。",
}

// propHints 是**有明确替代写法**的常见误解（键 "标签|属性"，"*" = 任意标签）。
//
// 与 eventsNotImplemented 同理：通用文案「未知属性」帮不上忙，用户要的是
// 「那我该怎么写」。每条都来自实扫证据，新增要带理由。
var propHints = map[string]string{
	"avatar|round":     "avatar 不认 round —— 要方的写 shape=\"square\"（缺省就是圆）",
	"button|label":     "button 不认 label —— 按钮文字要写成子节点 <button>确定</button>（label 只在 menu / menubar / menuitem 上是真属性）",
	"column|align":     "column 不认 align —— 交叉轴对齐用 alignItems，主轴用 justifyContent",
	"row|align":        "row 不认 align —— 交叉轴对齐用 alignItems，主轴用 justifyContent",
	"table|borderless": "borderless 由 table-row / table-cell 自己读，写在 <table> 上不生效",
	"table|zebra":      "table 不认 zebra —— 斑马纹由内核按行号自动写 _zebra，无法用 prop 开关",
}

// frameworkProps 是在 h() 里被指令层先消费的键（each/show/model/…）。
// 它们不进节点 Props 的读取路径，写它们是**正确用法**，不能报未知属性。
var frameworkProps = map[string]string{
	"each":     "each 指令：列表展开（gfx/directive.go / gfx/view.go）",
	"fallback": "each 指令的空列表兜底（gfx/view.go）",
	"key":      "each 指令的项标识：取值函数或字段名简写（gfx/view.go）",
	"model":    "model= 双向绑定：展开成该标签的受控 prop（gfx/model.go）",
	"show":     "show 指令：条件渲染（gfx/directive.go）",
	"stable":   "each 指令的稳定复用开关（gfx/directive.go）",
}

// eventExempt 是以 on 开头但**不是事件回调**的键（走 effect 求值的响应式
// 函数 prop）。isEventPropName 只判前缀，认不出这一层。
var eventExempt = map[string]string{
	"onDraw": "响应式绘制函数（wireDraw），不是事件回调（gfx/node.go）",
}

// propPrefixExempt 是不进本白名单、**由别的层**校验或本就不该校验的名字前缀。
var propPrefixExempt = []string{
	"__",
	"aria-",
	"data-",
}
