// Code generated by `gox types`. DO NOT EDIT.
//
// gox 内置模块与 JSX 元素的类型声明 (给 IDE / tsc 检查用)。
// gox 引擎运行时不需要这份文件: .tsx 在加载前由引擎自动剥离类型 (esbuild
// 转译, JSX 原样保留给引擎自己的降级管线)。
//
// 本文件是**全局脚本** (顶层没有 import/export), 这样 JSX 命名空间全局可见,
// .tsx 才认 <window> / <row> / <text> 这类内置标签。
//
// 类型精度: 内置导出多为 Go 闭包, 无法反射出参数/返回类型, 一律给
// (...args: any[]): any 并标注「类型待补」—— 这是刻意的: 宁可宽松, 也不编造。
// 需要精确签名时, 在业务代码里就近写 interface 收窄, 或见 docs/typescript.md。

declare module "fs" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function appendFile(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function appendFileSync(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function copyFileSync(...args: any[]): any;
  /** 类型待补: 默认导出 (内置常量, 类型未推断). */
  const _default: any;
  export default _default;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function existsSync(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function mkdir(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function mkdirSync(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function readBytesSync(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function readFile(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function readFileSync(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function readdir(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function readdirSync(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function renameSync(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function rmSync(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function rmdirSync(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function stat(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function statSync(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function unlink(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function unlinkSync(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function writeFile(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function writeFileSync(...args: any[]): any;
}

declare module "gox" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function Match(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function RouterLink(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function RouterView(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function Switch(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function above(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function alert(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function animate(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function appDataDir(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function appState(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function authorize(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function battery(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function below(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function between(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function breakpoint(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function breakpoints(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function canIUse(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function capabilities(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function checkForUpdate(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function checkPermission(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function chooseImage(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function chooseOneImage(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function chooseVideo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function cleanupBackup(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function clearAllWatches(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function clearStorage(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function clearWatch(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function clipboardReadText(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function clipboardWriteText(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function confirm(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function contentArea(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function createEffect(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function createMemo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function createResource(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function createRouter(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function createSignal(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function current(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function currentVersion(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function devEval(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function devLogs(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function devNode(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function devProps(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function devSnapshot(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function devStats(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function devTree(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function deviceId(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function deviceInfo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function distanceBetween(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function downloadAndInstall(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function exitApp(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function focusNext(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function focusNode(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function focusOrder(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function focusPrev(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function getBrightness(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function getLocation(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function getSetting(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function getStorage(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function getStorageInfo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function h(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function hasFold(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function hasLocation(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function hinge(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function hingeOrientation(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function humanSize(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function insets(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function isCharging(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function isCompactWidth(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function isExpandedWidth(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function isMediumWidth(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function isOnline(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function isSplit(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function isTabletLayout(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function keepScreenOn(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function keyboardHeight(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function keyboardVisible(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function lastLocation(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function layoutMode(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function lazy(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function locationPlatform(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function matchBreakpoint(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function mediaInfo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function multiWindow(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function network(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offAppStateChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offBackPress(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offBatteryChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offDisplayChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offMemoryWarning(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offNetworkChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offPermissionChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offViewportChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offWindowDisplayChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onAppStateChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onBackPress(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onBatteryChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onCleanup(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onDisplayChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onMemoryWarning(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onMount(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onNetworkChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onPermissionChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onViewportChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onWindowDisplayChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function openAppSettings(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function openContextMenu(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function openFile(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function openSystemSettings(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function permissionKinds(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function permissionState(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function platform(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function posture(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function previewImage(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function primaryScreen(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function regions(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function removeStorage(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function render(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportAppState(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportBackPress(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportBattery(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportLocation(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportMemoryWarning(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportNetwork(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportPermission(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportPosture(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportViewport(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function requestAnimationFrame(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function requestPermissions(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reservedRegions(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function resetBreakpoints(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function resetDisplays(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function resetViewport(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function roles(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function safeAreaStyle(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function saveFile(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function saveImage(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function screen(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function screenOf(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function screens(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function setAppName(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function setBreakpoints(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function setBrightness(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function setOrientation(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function setStorage(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function setTheme(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function share(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function splitInfo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function splitRatio(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function takePhoto(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function toggleDark(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function untrack(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useAppState(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useBattery(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useBreakpoint(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useDeviceInfo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useInsets(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useKeyboardHeight(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useLastLocation(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useLayoutMode(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useMultiWindow(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useNetwork(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function usePosture(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useReservedRegions(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useRoute(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useRouteState(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useRouter(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useScreen(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useScreens(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useViewport(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useWindowDisplay(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useWindowInfo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function vibrate(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function vibrateLong(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function vibrateShort(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function viewport(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function viewportModes(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function watchLocation(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function widthClass(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function window(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function windowInfo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function windows(...args: any[]): any;
}

declare module "gx/a11y" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function focusNext(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function focusNode(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function focusOrder(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function focusPrev(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function roles(...args: any[]): any;
}

declare module "gx/app" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function appState(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function exitApp(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offAppStateChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offBackPress(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offMemoryWarning(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onAppStateChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onBackPress(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onMemoryWarning(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportAppState(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportBackPress(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportMemoryWarning(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function setOrientation(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function share(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useAppState(...args: any[]): any;
}

declare module "gx/dev" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function devEval(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function devLogs(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function devNode(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function devProps(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function devSnapshot(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function devTree(...args: any[]): any;
}

declare module "gx/device" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function battery(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function canIUse(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function capabilities(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function deviceId(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function deviceInfo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function getBrightness(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function isCharging(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function isOnline(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function keepScreenOn(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function network(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offBatteryChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offNetworkChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onBatteryChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onNetworkChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function openSystemSettings(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportBattery(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportNetwork(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function setBrightness(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useBattery(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useDeviceInfo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useNetwork(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function vibrate(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function vibrateLong(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function vibrateShort(...args: any[]): any;
}

declare module "gx/dialog" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function alert(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function confirm(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function openFile(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function saveFile(...args: any[]): any;
}

declare module "gx/geo" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function clearAllWatches(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function clearWatch(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function distanceBetween(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function getLocation(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function hasLocation(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function lastLocation(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function locationPlatform(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportLocation(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useLastLocation(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function watchLocation(...args: any[]): any;
}

declare module "gx/gfx" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function animate(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function clipboardReadText(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function clipboardWriteText(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function h(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function openContextMenu(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function render(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function requestAnimationFrame(...args: any[]): any;
}

declare module "gx/media" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function chooseImage(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function chooseOneImage(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function chooseVideo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function humanSize(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function mediaInfo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function previewImage(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function saveImage(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function takePhoto(...args: any[]): any;
}

declare module "gx/permission" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function authorize(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function checkPermission(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function getSetting(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offPermissionChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onPermissionChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function openAppSettings(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function permissionKinds(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function permissionState(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportPermission(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function requestPermissions(...args: any[]): any;
}

declare module "gx/router" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function RouterLink(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function RouterView(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function createRouter(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function lazy(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useRoute(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useRouteState(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useRouter(...args: any[]): any;
}

declare module "gx/screen" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function hinge(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function hingeOrientation(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offDisplayChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offWindowDisplayChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onDisplayChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onWindowDisplayChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function platform(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function posture(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function primaryScreen(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function regions(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportPosture(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function resetDisplays(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function screen(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function screenOf(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function screens(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function splitRatio(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function usePosture(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useScreen(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useScreens(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useWindowDisplay(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useWindowInfo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function window(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function windowInfo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function windows(...args: any[]): any;
}

declare module "gx/solid" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function createEffect(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function createMemo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function createResource(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function createSignal(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function devStats(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onCleanup(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onMount(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function untrack(...args: any[]): any;
}

declare module "gx/storage" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function appDataDir(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function clearStorage(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function getStorage(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function getStorageInfo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function removeStorage(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function setAppName(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function setStorage(...args: any[]): any;
}

declare module "gx/theme" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function current(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function setTheme(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function toggleDark(...args: any[]): any;
}

declare module "gx/update" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function checkForUpdate(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function cleanupBackup(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function currentVersion(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function downloadAndInstall(...args: any[]): any;
}

declare module "gx/view" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function Match(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function Switch(...args: any[]): any;
}

declare module "gx/viewport" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function above(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function below(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function between(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function breakpoint(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function breakpoints(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function contentArea(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function hasFold(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function insets(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function isCompactWidth(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function isExpandedWidth(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function isMediumWidth(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function isSplit(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function isTabletLayout(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function keyboardHeight(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function keyboardVisible(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function layoutMode(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function matchBreakpoint(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function multiWindow(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function offViewportChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function onViewportChange(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reportViewport(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function reservedRegions(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function resetBreakpoints(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function resetViewport(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function safeAreaStyle(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function setBreakpoints(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function splitInfo(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useBreakpoint(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useInsets(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useKeyboardHeight(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useLayoutMode(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useMultiWindow(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useReservedRegions(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function useViewport(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function viewport(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function viewportModes(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function widthClass(...args: any[]): any;
}

declare module "http" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function createServer(...args: any[]): any;
  /** 类型待补: 默认导出 (内置常量, 类型未推断). */
  const _default: any;
  export default _default;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function get(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function request(...args: any[]): any;
}

declare module "path" {
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function basename(...args: any[]): any;
  /** 类型待补: 默认导出 (内置常量, 类型未推断). */
  const _default: any;
  export default _default;
  /** 类型待补: 运行时内置常量 (由 Go 注册, 类型未推断). */
  export const delimiter: any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function dirname(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function extname(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function isAbsolute(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function join(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function resolve(...args: any[]): any;
  /** 类型待补: 运行时内置常量 (由 Go 注册, 类型未推断). */
  export const sep: any;
}

declare module "process" {
  /** 类型待补: 运行时内置常量 (由 Go 注册, 类型未推断). */
  export const argv: any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function chdir(...args: any[]): any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function cwd(...args: any[]): any;
  /** 类型待补: 默认导出 (内置常量, 类型未推断). */
  const _default: any;
  export default _default;
  /** 类型待补: 运行时内置常量 (由 Go 注册, 类型未推断). */
  export const env: any;
  /** 类型待补: 运行时内置函数 (由 Go 注册, 参数/返回类型未推断). */
  export function exit(...args: any[]): any;
  /** 类型待补: 运行时内置常量 (由 Go 注册, 类型未推断). */
  export const pid: any;
  /** 类型待补: 运行时内置常量 (由 Go 注册, 类型未推断). */
  export const platform: any;
}

// ===== JSX 内置元素 (宽松) =====

interface GoxElementProps {
  onClick?: (e?: any) => void;
  onInput?: (e: { value: any }) => void;
  onChange?: (e: { value: any }) => void;
  onKeyDown?: (e: { key: string }) => void;
  onWheel?: (e: { deltaY: number; shift: boolean }) => void;
  [prop: string]: any;
}

declare namespace JSX {
  type Element = any;
  interface ElementChildrenAttribute {
    children: {};
  }
  interface IntrinsicElements {
    [tag: string]: GoxElementProps;
  }
}

// ===== 用户模块导出清单 (起点, 非类型推断) =====
// 说明: TS 全局 .d.ts 不能对相对模块做 ambient 声明 (TS2436), 故此处以清单
// 形式列出各模块的顶层导出名, 供手写 interface / 补全类型时参考。
// .ts/.tsx 的类型本就写在源文件里; 对 .js 模块, 这是补 d.ts 的起点。
//
//   app.tsx
//     export const App: any;
//   components/counter.tsx
//     export const Counter: any;
//   components/status-bar.tsx
//     export const StatusBar: any;
//   components/todo-list.tsx
//     export const TodoList: any;
//   store.ts
//     export const draft: any;
//     export const note: any;
//     export const setDraft: any;
//     export const setNote: any;
//     export const setTodos: any;
//     export const todos: any;
//   theme.ts
//     export const colors: any;
//     export const font: any;
//     export const space: any;
